config/routes.rb
Dem::Application.routes.draw do
  devise_for :users
get "home/index"
get "about" =>"home#about"
get "contactus" =>"home#contactus"
get "faq" =>"home#faq"
get "news" =>"home#news"
get "cows" =>"home#cows"

root to: "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end
	def about
    end
    def news
    end
    def cows
    end
    def faq
    end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/contactus.html.erb
<!DOCTYPE html>
<html>
<head>
 <link href="/assets/styliii.css?body=1" media="screen" rel="stylesheet" />
    <title>Contact form</title>
</head>
<body>
<div id="contact-form">
<h1>Contact us now!! </h1>
    <h2>Fill out The form below and get in touch with us</h2>
        <label for="name">Name: <span class="required">*</span></label>
        <input type="text" id="name" name="name" value="" placeholder="Your Name" required="required" autofocus="autofocus" />
         
        <label for="email">Email Address: <span class="required">*</span></label>
        <input type="email" id="email" name="email" value="" placeholder="youremail@example.com" required="required" />
         
        <label for="telephone">Telephone: </label>
        <input type="tel" id="telephone" name="telephone" value="" placeholder="0700000000" />
         
        <label for="enquiry">Enquiry:</label>
        <select id="enquiry" name="enquiry">
            <option value="general">General</option>
            <option value="complaint">Complaint</option>
            <option value="compliment">Compliment</option>
        </select>
         
        <label for="message">Message: <span class="required">*</span></label>
        <textarea id="message" name="message" placeholder="Your message must not be less than 20 charcters" required="required" data-minlength="20"></textarea>
        <input type="submit" value="Submit" id="submit-button" />
        <p id="req-field-desc"><span class="required">*</span> indicates a required field</p>
    </form>
</div>

</body>
</html>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dem</title>
    <%= javascript_include_tag '/assets/jquery-1.10.js' %>
  <link href="/assets/css.css?body=1" media="screen" rel="stylesheet" />d
  <%= javascript_include_tag '/assets/jquery.cycle.all.js' %>
  <script>
$(document).ready(function() {
    $('#image').cycle({ 
	fx:    'fade', // choose your transition type, ex: fade, scrollUp, shuffle, etc...
    next:  '#right', 
    
	});
});
  </script>

</head>
<body>
<div id="user">
<% if user_signed_in? %>
Signed in as <%= current_user.email %>.Not you?
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<% else %>
<%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
<% end %>
	
</div>
<% flash.each do |name, msg| %>
<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<div id="container">

	<div id="ernst">
		<ul id="navmenu">
			<li><%= link_to_unless_current("HOME",root_path) %></li>
			<li><%= link_to_unless_current("ABOUT US",about_path ) %></li>
			<li><%= link_to_unless_current("COWS",cows_path) %></li>
			<li><%= link_to_unless_current("CONTACTUS",contactus_path) %></li>
			<li><%= link_to_unless_current("FAQ",faq_path) %></li>
			

		</ul>

	</div>
<div id="image">
	<%=image_tag "img1.jpg"%>

</div>


<%= yield %>
</div>
<div id="footer">
		<div class="table">
		<ul id="horizon-list">
			<li><a href="#">Home|</a></li>
			<li><a href="#">Contactus|</a></li>
			<li><a href="#">FAQ|</a></li>
			<li><a href="#">Services|</a></li>
			<li><a href="#">Complaints|</a></li>
			<li><a href="#">Compliments|</a></li><br/><br/>

			</ul>
              
			</div>
		</div><!--end of footer-->	

</body>
</html>